version: '3.4'

services:
  aidataanalysiscourse:
    image: aidataanalysiscourse
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
