name: ai-data-course-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.6
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - nbconvert
  - pip:
      - myst-nb
      - jupyterlab-myst
      - hide_code
      - ipywidgets